[general]
import = [
	"~/.config/alacritty/current_font.toml",
	"~/.config/alacritty/current_theme.toml"
]
live_config_reload = true

[window]
blur = true
decorations = "Buttonless"
opacity = 0.92
option_as_alt = "Both"
padding.x = 8
padding.y = 8
startup_mode = "Windowed"

[scrolling]
history = 25000

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

##
## Keyboard (MacOS)
##

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "+"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "-"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "0"
mods = "Command"
